name: Check Pipelines for Variable Group

on:
  
  workflow_dispatch:

jobs:
  check_pipelines:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run the script
      env:
        AZURE_DEVOPS_ORGANIZATION: cybagedevops
        AZURE_DEVOPS_PROJECT: MIS
        AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        VARIABLE_GROUP_ID: 98
      run: python check_pipelines.py
