name: Demo

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyYAML
        pip install requests

    - name: Run the script
      run: |
        python find_variable_group_usage.py
      env:
        AZURE_DEVOPS_ORGANIZATION: cybagedevops
        AZURE_DEVOPS_PROJECT: MIS
        AZURE_DEVOPS_PAT: ${{ secrets.AZURE_PAT }}
