name: Azure DevOps Variable Groups

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
    inputs:
      organization:  # Input for Azure DevOps organization name
        description: 'Azure DevOps organization name'
        required: true
        default: 'cybagedevops'
      project:  # Input for Azure DevOps project name
        description: 'Azure DevOps project name'
        required: true
        default: 'MIS'

jobs:
  list-variable-groups:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install requests library
      run: python -m pip install requests

    - name: List Variable Groups
      id: list-groups
      run: |
        import requests
        import os

        organization = "${{ github.event.inputs.organization }}"
        project = "${{ github.event.inputs.project }}"

        url = f"https://dev.azure.com/{organization}/{project}/_apis/distributedtask/variablegroups?api-version=6.0-preview.2"

        headers = {
            "Authorization": f"Basic {os.environ['AZURE_DEVOPS_EXT_PAT']}",
            "Content-Type": "application/json"
        }

        response = requests.get(url, headers=headers)
        response.raise_for_status()

        variable_groups = response.json()['value']
        for group in variable_groups:
            print(f"Name: {group['name']}, ID: {group['id']}")

      env:
        AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}  # Personal Access Token (PAT) with appropriate permissions
