name: Azure DevOps Variable Groups

on:
  workflow_dispatch:  # Manual trigger

jobs:
  list-variable-groups:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install requests library
      run: python -m pip install requests

    - name: List Variable Groups
      id: list-groups
      run: |
        import requests
        import os

        organization = "cybagedevops"  # Replace with your organization name
        project = "MIS"           # Replace with your project name

        url = f"https://dev.azure.com/{organization}/{project}/_apis/distributedtask/variablegroups?api-version=7.1-preview.2"
               
        headers = {
            "Authorization": f"Basic {os.environ['AZURE_DEVOPS_EXT_PAT']}",
            "Content-Type": "application/json"
        }

        response = requests.get(url, headers=headers)
        response.raise_for_status()

        variable_groups = response.json()['value']
        for group in variable_groups:
            print(f"Name: {group['name']}, ID: {group['id']}")

      env:
        AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}  # Personal Access Token (PAT) with appropriate permissions

