name: Manage Team Permissions

on:
  push:
    branches:
      - main  

jobs:
  manage-permissions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up GitHub CLI
      uses: wusatosi/setup-gh@v1.1
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Run permission management script
      run: |
        #!/bin/bash

        # Define your organization, repository, and team with its permission
        ORG="DevopsCyb"
        REPO="WebAPiProject" 
        TEAM="CTG-Team"
        PERMISSION="push"

      
        # Function to remove all permissions for a team from a repository
        remove_permissions() {
          local repo=$1
          local team=$2
          gh api -X DELETE \
            -H "Accept: application/vnd.github.v3+json" \
            "/orgs/$ORG/teams/$team/repos/$ORG/$repo"
        }

        # Remove all permissions for the specified team from the repository
        echo "Removing all permissions for team $TEAM from repository $REPO"
        remove_permissions "$REPO" "$TEAM"

        # Grant new permission to the team for the repository
        echo "Granting $PERMISSION permission to team $TEAM for repository $REPO"
        gh api -X PUT \
          "/orgs/$ORG/teams/$TEAM/repos/$ORG/$REPO" \
          -f permission="$PERMISSION"

        echo "Permissions updated for $TEAM with $PERMISSION permission on the repository $REPO."
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
