name: Manage Team Permissions

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  manage-permissions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up GitHub CLI
      uses: wusatosi/setup-gh@v1.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run permission management script
      run: |
        #!/bin/bash

        # Define your organization, repository, and team with its permission
        ORG="DevopsCyb"
        REPO="WebAPiProject"
        TEAM="CTG-Team"
        PERMISSION="push"

      
        # Grant new permission to the team for the repository
        echo "Granting $PERMISSION permission to team $TEAM for repository $REPO"
        gh api -X PUT \
          -H "Accept: application/vnd.github.v3+json" \
          "/orgs/$ORG/teams/$TEAM/repos/$ORG/$REPO" \
          -f permission="$PERMISSION"

        echo "Permissions updated for $TEAM with $PERMISSION permission on the repository $REPO."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub Actions token
