
name: Manage GitHub Repo Permissions

on:
  workflow_dispatch:  # allows manual triggering of the workflow

jobs:
  manage-permissions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run GitHub Permissions Script
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
        GITHUB_ORG: ${{ secrets.GH_ORG }}
      run: |
        python github_permissions.py
